name: jugglyng

channels:
- conda-forge

dependencies:
- python=3.9
# Graphiques
- jupyter
- jupyterlab
- notebook
- ipywidgets
- pythreejs
# Algorithme de composition
- numpy
- cppyy
- sage
- pip
- pip:
  - recordclass==0.14.3
  # Son
  - jp_proxy_widget
# Autres
- pylatex
