#!/bin/bash

mamba activate jugglyng
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jp_proxy_widget
jupyter lab build

cd "Expérimentations/Juggling DLX/DLX"
make lib
